baseURL = 'https://cplus-hub.github.io/Travel/'
languageCode = 'zh-tw'
title = 'My Travel Blog'
theme = 'ananke'
buildFuture = true
disablePathToLower = true

[params]
  custom_css = ["css/dark-mode.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true